### ISSUE TITLE
Fix deprecation issues

### ISSUE THREAD

**Issue by loganphillips792** [befriend-app/befriend-app#3]
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($places_spinner_dim, 2) or calc($places_spinner_dim / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
77 │         left: calc(50% - #{$places_spinner_dim / 2});
   │                            ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    app/scss/places.scss 77:28  @import
    app/scss/styles.scss 10:9   root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($places_spinner_dim, 2) or calc($places_spinner_dim / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
78 │         top: calc(50% - #{$places_spinner_dim / 2} - #{$places_header_h});
   │                           ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    app/scss/places.scss 78:27  @import
    app/scss/styles.scss 10:9   root stylesheet

**Comment by eugenelight16** [comment]
Commit 3290089 removes the deprecation warning.
